package com.example.jmora.webservicesoap.Models;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.example.jmora.webservicesoap.Models.PisoDao;
import com.example.jmora.webservicesoap.Models.SectorDao;
import com.example.jmora.webservicesoap.Models.EmpleadoDao;
import com.example.jmora.webservicesoap.Models.GrupoDao;
import com.example.jmora.webservicesoap.Models.GrupoEmpleadoDao;
import com.example.jmora.webservicesoap.Models.HomeDao;
import com.example.jmora.webservicesoap.Models.DiasSemanaDao;
import com.example.jmora.webservicesoap.Models.EmpleadoQueueDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 3): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 3;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        PisoDao.createTable(db, ifNotExists);
        SectorDao.createTable(db, ifNotExists);
        EmpleadoDao.createTable(db, ifNotExists);
        GrupoDao.createTable(db, ifNotExists);
        GrupoEmpleadoDao.createTable(db, ifNotExists);
        HomeDao.createTable(db, ifNotExists);
        DiasSemanaDao.createTable(db, ifNotExists);
        EmpleadoQueueDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        PisoDao.dropTable(db, ifExists);
        SectorDao.dropTable(db, ifExists);
        EmpleadoDao.dropTable(db, ifExists);
        GrupoDao.dropTable(db, ifExists);
        GrupoEmpleadoDao.dropTable(db, ifExists);
        HomeDao.dropTable(db, ifExists);
        DiasSemanaDao.dropTable(db, ifExists);
        EmpleadoQueueDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(PisoDao.class);
        registerDaoClass(SectorDao.class);
        registerDaoClass(EmpleadoDao.class);
        registerDaoClass(GrupoDao.class);
        registerDaoClass(GrupoEmpleadoDao.class);
        registerDaoClass(HomeDao.class);
        registerDaoClass(DiasSemanaDao.class);
        registerDaoClass(EmpleadoQueueDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
