package com.example.jmora.webservicesoap.Models;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.jmora.webservicesoap.Models.Piso;
import com.example.jmora.webservicesoap.Models.Sector;
import com.example.jmora.webservicesoap.Models.Empleado;
import com.example.jmora.webservicesoap.Models.Grupo;
import com.example.jmora.webservicesoap.Models.GrupoEmpleado;
import com.example.jmora.webservicesoap.Models.Home;
import com.example.jmora.webservicesoap.Models.DiasSemana;
import com.example.jmora.webservicesoap.Models.EmpleadoQueue;

import com.example.jmora.webservicesoap.Models.PisoDao;
import com.example.jmora.webservicesoap.Models.SectorDao;
import com.example.jmora.webservicesoap.Models.EmpleadoDao;
import com.example.jmora.webservicesoap.Models.GrupoDao;
import com.example.jmora.webservicesoap.Models.GrupoEmpleadoDao;
import com.example.jmora.webservicesoap.Models.HomeDao;
import com.example.jmora.webservicesoap.Models.DiasSemanaDao;
import com.example.jmora.webservicesoap.Models.EmpleadoQueueDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pisoDaoConfig;
    private final DaoConfig sectorDaoConfig;
    private final DaoConfig empleadoDaoConfig;
    private final DaoConfig grupoDaoConfig;
    private final DaoConfig grupoEmpleadoDaoConfig;
    private final DaoConfig homeDaoConfig;
    private final DaoConfig diasSemanaDaoConfig;
    private final DaoConfig empleadoQueueDaoConfig;

    private final PisoDao pisoDao;
    private final SectorDao sectorDao;
    private final EmpleadoDao empleadoDao;
    private final GrupoDao grupoDao;
    private final GrupoEmpleadoDao grupoEmpleadoDao;
    private final HomeDao homeDao;
    private final DiasSemanaDao diasSemanaDao;
    private final EmpleadoQueueDao empleadoQueueDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pisoDaoConfig = daoConfigMap.get(PisoDao.class).clone();
        pisoDaoConfig.initIdentityScope(type);

        sectorDaoConfig = daoConfigMap.get(SectorDao.class).clone();
        sectorDaoConfig.initIdentityScope(type);

        empleadoDaoConfig = daoConfigMap.get(EmpleadoDao.class).clone();
        empleadoDaoConfig.initIdentityScope(type);

        grupoDaoConfig = daoConfigMap.get(GrupoDao.class).clone();
        grupoDaoConfig.initIdentityScope(type);

        grupoEmpleadoDaoConfig = daoConfigMap.get(GrupoEmpleadoDao.class).clone();
        grupoEmpleadoDaoConfig.initIdentityScope(type);

        homeDaoConfig = daoConfigMap.get(HomeDao.class).clone();
        homeDaoConfig.initIdentityScope(type);

        diasSemanaDaoConfig = daoConfigMap.get(DiasSemanaDao.class).clone();
        diasSemanaDaoConfig.initIdentityScope(type);

        empleadoQueueDaoConfig = daoConfigMap.get(EmpleadoQueueDao.class).clone();
        empleadoQueueDaoConfig.initIdentityScope(type);

        pisoDao = new PisoDao(pisoDaoConfig, this);
        sectorDao = new SectorDao(sectorDaoConfig, this);
        empleadoDao = new EmpleadoDao(empleadoDaoConfig, this);
        grupoDao = new GrupoDao(grupoDaoConfig, this);
        grupoEmpleadoDao = new GrupoEmpleadoDao(grupoEmpleadoDaoConfig, this);
        homeDao = new HomeDao(homeDaoConfig, this);
        diasSemanaDao = new DiasSemanaDao(diasSemanaDaoConfig, this);
        empleadoQueueDao = new EmpleadoQueueDao(empleadoQueueDaoConfig, this);

        registerDao(Piso.class, pisoDao);
        registerDao(Sector.class, sectorDao);
        registerDao(Empleado.class, empleadoDao);
        registerDao(Grupo.class, grupoDao);
        registerDao(GrupoEmpleado.class, grupoEmpleadoDao);
        registerDao(Home.class, homeDao);
        registerDao(DiasSemana.class, diasSemanaDao);
        registerDao(EmpleadoQueue.class, empleadoQueueDao);
    }
    
    public void clear() {
        pisoDaoConfig.getIdentityScope().clear();
        sectorDaoConfig.getIdentityScope().clear();
        empleadoDaoConfig.getIdentityScope().clear();
        grupoDaoConfig.getIdentityScope().clear();
        grupoEmpleadoDaoConfig.getIdentityScope().clear();
        homeDaoConfig.getIdentityScope().clear();
        diasSemanaDaoConfig.getIdentityScope().clear();
        empleadoQueueDaoConfig.getIdentityScope().clear();
    }

    public PisoDao getPisoDao() {
        return pisoDao;
    }

    public SectorDao getSectorDao() {
        return sectorDao;
    }

    public EmpleadoDao getEmpleadoDao() {
        return empleadoDao;
    }

    public GrupoDao getGrupoDao() {
        return grupoDao;
    }

    public GrupoEmpleadoDao getGrupoEmpleadoDao() {
        return grupoEmpleadoDao;
    }

    public HomeDao getHomeDao() {
        return homeDao;
    }

    public DiasSemanaDao getDiasSemanaDao() {
        return diasSemanaDao;
    }

    public EmpleadoQueueDao getEmpleadoQueueDao() {
        return empleadoQueueDao;
    }

}
