package com.example.jmora.webservicesoap.Models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EMPLEADO_QUEUE".
 */
public class EmpleadoQueue {

    private Long dni_empleado;
    private String nombre;
    private String apellido;
    private java.util.Date fecha_de_nacimiento;
    private String sexo;
    private Long id_sector;
    private String password;

    public EmpleadoQueue() {
    }

    public EmpleadoQueue(Long dni_empleado) {
        this.dni_empleado = dni_empleado;
    }

    public EmpleadoQueue(Long dni_empleado, String nombre, String apellido, java.util.Date fecha_de_nacimiento, String sexo, Long id_sector, String password) {
        this.dni_empleado = dni_empleado;
        this.nombre = nombre;
        this.apellido = apellido;
        this.fecha_de_nacimiento = fecha_de_nacimiento;
        this.sexo = sexo;
        this.id_sector = id_sector;
        this.password = password;
    }

    public Long getDni_empleado() {
        return dni_empleado;
    }

    public void setDni_empleado(Long dni_empleado) {
        this.dni_empleado = dni_empleado;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getApellido() {
        return apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public java.util.Date getFecha_de_nacimiento() {
        return fecha_de_nacimiento;
    }

    public void setFecha_de_nacimiento(java.util.Date fecha_de_nacimiento) {
        this.fecha_de_nacimiento = fecha_de_nacimiento;
    }

    public String getSexo() {
        return sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    public Long getId_sector() {
        return id_sector;
    }

    public void setId_sector(Long id_sector) {
        this.id_sector = id_sector;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

}
