package com.example.jmora.webservicesoap.Models;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.jmora.webservicesoap.Models.Grupo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GRUPO".
*/
public class GrupoDao extends AbstractDao<Grupo, Long> {

    public static final String TABLENAME = "GRUPO";

    /**
     * Properties of entity Grupo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id_grupo = new Property(0, Long.class, "id_grupo", true, "ID_GRUPO");
        public final static Property Nombre_grupo = new Property(1, String.class, "nombre_grupo", false, "NOMBRE_GRUPO");
        public final static Property Estado = new Property(2, Integer.class, "estado", false, "ESTADO");
    };

    private DaoSession daoSession;


    public GrupoDao(DaoConfig config) {
        super(config);
    }
    
    public GrupoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GRUPO\" (" + //
                "\"ID_GRUPO\" INTEGER PRIMARY KEY ," + // 0: id_grupo
                "\"NOMBRE_GRUPO\" TEXT," + // 1: nombre_grupo
                "\"ESTADO\" INTEGER);"); // 2: estado
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GRUPO\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Grupo entity) {
        stmt.clearBindings();
 
        Long id_grupo = entity.getId_grupo();
        if (id_grupo != null) {
            stmt.bindLong(1, id_grupo);
        }
 
        String nombre_grupo = entity.getNombre_grupo();
        if (nombre_grupo != null) {
            stmt.bindString(2, nombre_grupo);
        }
 
        Integer estado = entity.getEstado();
        if (estado != null) {
            stmt.bindLong(3, estado);
        }
    }

    @Override
    protected void attachEntity(Grupo entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Grupo readEntity(Cursor cursor, int offset) {
        Grupo entity = new Grupo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id_grupo
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // nombre_grupo
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2) // estado
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Grupo entity, int offset) {
        entity.setId_grupo(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNombre_grupo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setEstado(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Grupo entity, long rowId) {
        entity.setId_grupo(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Grupo entity) {
        if(entity != null) {
            return entity.getId_grupo();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
